<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Stats;
use Doctrine\ORM\Repository;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\ResultSetMapping;
use AppBundle\Repository\StatsRepository;





/**
 * StatsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatsRepository extends EntityRepository
{


    public function getStatistics(){

        $rsm = new ResultSetMapping;
        $rsm->addEntityResult('AppBundle:Stats','s');
        $rsm->addFieldResult('s','player','player');
        $rsm->addFieldResult('s','win','win');
        $rsm->addFieldResult('s','lose','lose');
        $rsm->addFieldResult('s','draw','draw');
        $rsm->addFieldResult('s','rocks','rocks');
        $rsm->addFieldResult('s','papers','papers');
        $rsm->addFieldResult('s','scissors','scissors');
        $rsm->addFieldResult('s','lizards','lizards');
        $rsm->addFieldResult('s','spocks','spocks');

        $query = $this->_em->createNativeQuery(
            'SELECT
          (SELECT name FROM player WHERE id = player_id) as player,
          SUM(CASE WHEN result = 1 THEN 1 ELSE 0 END ) as win,
          SUM(CASE WHEN result = 0 THEN 1 ELSE 0 END ) as lose,
          SUM(CASE WHEN result = 2 THEN 1 ELSE 0 END ) as draw,
          SUM(CASE WHEN threw = \'Rock\' THEN 1 ELSE 0 END ) as rocks,
          SUM(CASE WHEN threw = \'Paper\' THEN 1 ELSE 0 END ) as papers,
          SUM(CASE WHEN threw = \'Scissors\' THEN 1 ELSE 0 END ) as scissors,
          SUM(CASE WHEN threw = \'Lizard\' THEN 1 ELSE 0 END ) as lizards,
          SUM(CASE WHEN threw = \'Spock\' THEN 1 ELSE 0 END ) as spocks
        FROM stat s
        GROUP BY player_id
        ORDER BY player_id',$rsm);

        return $query->getResult();


    }
}
