AppBundle\Entity\Stat:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\StatRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        playerId:
            type: integer
        threw:
            type: string
            length: '25'
        result:
            type: integer
    lifecycleCallbacks: {  }
